### ISSUE TITLE
Look very good and promising - A suggested feature

### ISSUE THREAD

**Issue by TheStigh** [ErfanDL/ESP_OTA_Dashboard#2]
Hello @ErfanDL came over this nice piece of solution for OTA of remote ESP32's. I have a great suggestion that would highly improve this solution - supporting GROUPS. Being able to add the ESP'2 to groups for group based updating would be a good upgrade and a good solution if a person do have multiple ESP's.

Is this something that you have looked into?

**Comment by ErfanDL** [comment]
> Hello @ErfanDL came over this nice piece of solution for OTA of remote ESP32's. I have a great suggestion that would highly improve this solution - supporting GROUPS. Being able to add the ESP'2 to groups for group based updating would be a good upgrade and a good solution if a person do have multiple ESP's.
> 
> Is this something that you have looked into?

Hi @TheStigh I am glad that you like this project. I have considered this feature in the list of server features that will be provided during future updates.

**Comment by TheStigh** [comment]
Have some good ideas I can share how this tool will suddenly be more advanced but cover a lot of areas of usage. Can you pls share your email and we can keep in touch there?

**Comment by ErfanDL** [comment]
> Have some good ideas I can share how this tool will suddenly be more advanced but cover a lot of areas of usage. Can you pls share your email and we can keep in touch there?

I will definitely be happy to cooperate in this regard. parsiyashabake@gmail.com
