### ISSUE TITLE
Failed to fetch command from the server. HTTP error: 

### ISSUE THREAD

**Issue by jkcontrol** [ErfanDL/ESP_OTA_Dashboard#5]
After uploading the first code to esp32 to make the ESP appear in the server, it prints these messages below and I cannot solve it!
Help please!

"Failed to fetch command from the server. HTTP error: connection refused"
"Failed to send heartbeat to Node.js server. HTTP error: connection refused"
"Failed to connect to Node.js server. HTTP error: connection refused"
"HTTP error code: -1"

**Comment by ErfanDL** [comment]
it's your server side problem ! please check your firewall setting to allowing port 3000.
